# This is used by Google Cloud ML
trainingInput:
  scaleTier: CUSTOM
  masterType: complex_model_l
  workerCount: 3
  workerType: complex_model_m
  parameterServerCount: 3
  parameterServerType: large_model
